name: Itunes App CD
on:
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use NodeJS ${{ matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: get branch name
        shell: bash
        run: echo ::set-output name=branch::${{github.event.pull_request.head.ref}}
        id: branch

      - name: configuration of AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: export BRANCH_NAME=${{ steps.branch.outputs.branch }} && yarn build:uat

      - name: Deploy to s3
        run: aws s3 sync ./build s3://dp-uat/${{ steps.branch.outputs.branch }}
    
